<?php
declare(strict_types=1);

namespace H42\WhimCMS\Template\Directives;

use H42\WhimCMS\Template\Directive;
use H42\WhimCMS\Template\Engine;
use H42\WhimCMS\Template\Expression;
use H42\WhimCMS\Template\Renderer;
use H42\WhimCMS\Template\Sanitizer;
use H42\WhimCMS\Template\Token;

/**
 * `{% html: <expr> %}` — emit a value as HTML, verbatim.
 *
 * Distinct from both `{{ var }}` (full HTML escape) and `{!! var !!}`
 * (em-only sanitiser, designed for short i18n strings with one
 * highlighted word). This directive performs **no** output-side
 * sanitisation; the value is emitted as-is.
 *
 * Audit contract — this directive is safe ONLY when the expression
 * resolves to HTML that has already been produced by trusted server-side
 * rendering with its own allowlist. Today the single legitimate use is
 * a Block's pre-rendered Markdown body (`H42\WhimCMS\Content\Block::$body`),
 * which is generated by `H42\WhimCMS\Content\Markdown` from a strict
 * whitelist of tags + attributes, with all literal text and href values
 * htmlspecialchars-escaped at construction time.
 *
 * Do NOT use this directive on:
 *   - i18n strings (use `{{ }}` for plain or `{!! !!}` for em-highlight)
 *   - block attribute values (those are author-controlled but plain text)
 *   - form input echoes (always `{{ }}`)
 *   - any value derived from `$_GET` / `$_POST` / `$_SERVER`
 *
 * Non-string values stringify via `Sanitizer::stringify()`, which renders
 * arrays / objects as the empty string — defence-in-depth so a wrong
 * type cannot leak `Array` text or trigger conversion warnings.
 *
 * In text-mode renders (`Engine::renderText`) tags are stripped, entities
 * decoded, and runs of whitespace collapsed — so a Markdown block body
 * that looks fine in an HTML mail comes through as readable plain text in
 * the alt-part instead of leaking literal `<p>` etc.
 */
final class HtmlDirective implements Directive
{
    public function keywords(): array
    {
        return ['html'];
    }

    public function tokenize(string $keyword, array $args): Token
    {
        return new Token('html', ['expr' => $args['html']]);
    }

    public function handles(): array
    {
        return ['html'];
    }

    public function render(Token $token, array $ctx, Renderer $renderer): string
    {
        $value = Expression::evaluate((string)$token->payload['expr'], $ctx);
        $str   = Sanitizer::stringify($value);

        if (empty($ctx[Engine::TEXT_MODE_FLAG])) {
            return $str;
        }

        // Text-mode: drop tags, decode entities, collapse whitespace.
        // Insert a space before stripping so adjacent block tags don't
        // run their text contents together (`<p>a</p><p>b</p>` → `a b`).
        $withSpaces = preg_replace('/</', ' <', $str) ?? $str;
        $stripped   = strip_tags($withSpaces);
        $decoded    = html_entity_decode($stripped, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        return trim((string)preg_replace('/\s+/u', ' ', $decoded));
    }

    public function renderBlock(Token $open, array $body, array $ctx, Renderer $renderer): string
    {
        throw new \LogicException('HtmlDirective is not a block directive.');
    }
}
