<?php
declare(strict_types=1);

namespace H42\WhimAdmin\Config;

use H42\WhimCMS\Content\Identifiers;

/**
 * Safe writer for the WhimCMS core's PHP-array config files.
 *
 * WhimAdmin only writes TWO of the core's config files:
 *
 *   - `config/routes.php`  (URL segment → slug, per language)
 *   - `config/i18n.php`    (`supported_langs`, `default_lang`, `detect_lang`)
 *
 * Everything else stays operator-managed. Each writer call:
 *
 *   1. Validates the target path is one of those two whitelisted files.
 *   2. Validates the in-memory array against the expected shape.
 *   3. Renders to a deterministic, human-readable PHP literal that
 *      re-`require`s back to the same array (round-trip stable).
 *   4. Atomic-writes via tempfile + rename, mode 0o644 on the final
 *      file (must be readable by Apache).
 *
 * Comments in the existing config file are NOT preserved — the writer
 * regenerates the file from data. The header banner emitted by
 * `render()` documents this so an operator who SSHes into the file
 * doesn't think their commentary was scrubbed silently.
 *
 * Format choice: arrays are emitted with the modern `[]` syntax,
 * indented two spaces per level, keys quoted with single quotes,
 * strings escaped via `addslashes` plus a NUL/CR/LF reject. Numbers
 * and booleans are emitted as literal `123` / `true`. No object or
 * resource serialisation — those would not round-trip via require.
 */
final class PhpArrayWriter
{
    public const TARGET_ROUTES = 'routes';
    public const TARGET_I18N   = 'i18n';

    public function __construct(private string $coreConfigDir)
    {
        if (realpath($coreConfigDir) === false) {
            throw new \RuntimeException("Core config dir not found: {$coreConfigDir}");
        }
    }

    /**
     * @param array<string, mixed> $payload
     */
    public function write(string $target, array $payload): void
    {
        $path = $this->pathFor($target);
        $this->validateShape($target, $payload);

        $body = $this->render($target, $payload);

        // Sanity round-trip: the bytes we're about to write must
        // re-`include` to the same array. Catches any serialiser bug
        // before it lands on disk.
        $tmpDir = sys_get_temp_dir();
        $probe  = $tmpDir . DIRECTORY_SEPARATOR . 'whimadmin-cfg-probe-' . bin2hex(random_bytes(6)) . '.php';
        if (@file_put_contents($probe, $body) === false) {
            throw new \RuntimeException('Cannot write probe file for round-trip check.');
        }
        try {
            /** @var mixed $reloaded */
            $reloaded = require $probe;
        } finally {
            @unlink($probe);
        }
        if ($reloaded !== $payload) {
            throw new \RuntimeException('Config-array serialiser produced a non-round-tripping value.');
        }

        // Atomic rename in core config dir.
        $tmp = $path . '.tmp.' . bin2hex(random_bytes(6));
        if (@file_put_contents($tmp, $body, LOCK_EX) === false) {
            throw new \RuntimeException("Cannot write config file (tempfile): {$path}");
        }
        @chmod($tmp, 0o644);
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new \RuntimeException("Cannot finalise config file: {$path}");
        }
    }

    /**
     * @param array<string, mixed> $payload
     */
    public function render(string $target, array $payload): string
    {
        $banner = "<?php\ndeclare(strict_types=1);\n\n"
            . "// Generated by WhimAdmin. Edit via the admin UI; manual edits to\n"
            . "// this file are preserved on next read but lost on next admin write.\n\n"
            . "return ";
        return $banner . $this->renderValue($payload, 0) . ";\n";
    }

    private function pathFor(string $target): string
    {
        $whitelist = [self::TARGET_ROUTES, self::TARGET_I18N];
        if (!in_array($target, $whitelist, true)) {
            throw new \InvalidArgumentException("Target '{$target}' is not a whimadmin-writable config file.");
        }
        return $this->coreConfigDir . DIRECTORY_SEPARATOR . $target . '.php';
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function validateShape(string $target, array $payload): void
    {
        if ($target === self::TARGET_ROUTES) {
            $routes = $payload['routes'] ?? null;
            if (!is_array($routes)) {
                throw new \RuntimeException("routes.php payload must have 'routes' as an array.");
            }
            foreach ($routes as $lang => $map) {
                if (!is_string($lang) || !Identifiers::isValidLang($lang)) {
                    throw new \RuntimeException("Bad language key in routes: '{$lang}'.");
                }
                if (!is_array($map)) {
                    throw new \RuntimeException("Routes for '{$lang}' must be a map.");
                }
                foreach ($map as $segment => $slug) {
                    if (!is_string($segment)) {
                        throw new \RuntimeException("Route segment must be a string in '{$lang}'.");
                    }
                    // Allow empty (=home), single segment, or multi-segment with /.
                    // Char set keeps it URL-safe and excludes control bytes.
                    // Segment shape is route-specific, not an identifier; kept inline.
                    if ($segment !== '' && preg_match('#^[a-zA-Z0-9_/-]{1,64}$#', $segment) !== 1) {
                        throw new \RuntimeException("Bad route segment '{$segment}' in '{$lang}'.");
                    }
                    if (!is_string($slug) || !Identifiers::isValidSlug($slug)) {
                        throw new \RuntimeException("Bad slug '" . (is_string($slug) ? $slug : '(non-string)') . "' for segment '{$segment}'.");
                    }
                }
            }
            // No other top-level keys.
            foreach (array_keys($payload) as $k) {
                if ($k !== 'routes') {
                    throw new \RuntimeException("Unexpected top-level key in routes payload: '{$k}'.");
                }
            }
            return;
        }

        if ($target === self::TARGET_I18N) {
            $allowed = ['supported_langs', 'default_lang', 'detect_lang'];
            foreach (array_keys($payload) as $k) {
                if (!in_array($k, $allowed, true)) {
                    throw new \RuntimeException("Unexpected top-level key in i18n payload: '{$k}'.");
                }
            }
            $supported = $payload['supported_langs'] ?? null;
            if (!is_array($supported) || $supported === []) {
                throw new \RuntimeException("i18n.supported_langs must be a non-empty list.");
            }
            foreach ($supported as $l) {
                if (!is_string($l) || !Identifiers::isValidLang($l)) {
                    throw new \RuntimeException("Bad supported_langs entry: '" . (is_string($l) ? $l : '(non-string)') . "'.");
                }
            }
            $default = $payload['default_lang'] ?? null;
            if ($default !== null && (!is_string($default) || !in_array($default, $supported, true))) {
                throw new \RuntimeException("default_lang must be one of supported_langs.");
            }
            $detect = $payload['detect_lang'] ?? null;
            if ($detect !== null && !is_bool($detect)) {
                throw new \RuntimeException("detect_lang must be boolean.");
            }
            return;
        }
    }

    /**
     * Hard caps for the writer. Both `routes.php` and `i18n.php`
     * carry strictly bounded data (URL segments, slugs, 2-letter
     * lang codes, booleans). The caps are far above what real
     * payloads need; their job is to refuse pathological inputs
     * before they reach the temp file.
     */
    private const MAX_STRING_LEN  = 4096;   // bytes per string value
    private const MAX_RECURSION   = 4;      // structural depth cap
    private const MAX_INT_ABS     = 1_000_000_000;

    private function renderValue(mixed $v, int $indent, int $depth = 0): string
    {
        if ($depth > self::MAX_RECURSION) {
            throw new \RuntimeException(
                'Config payload exceeds maximum recursion depth ' . self::MAX_RECURSION . '.'
            );
        }
        if (is_string($v)) {
            return self::renderStringLiteral($v);
        }
        if (is_int($v)) {
            if ($v < -self::MAX_INT_ABS || $v > self::MAX_INT_ABS) {
                throw new \RuntimeException('Integer out of bounds in config payload.');
            }
            return (string)$v;
        }
        if (is_float($v)) {
            if (!is_finite($v)) {
                throw new \RuntimeException('Non-finite float in config payload.');
            }
            return (string)$v;
        }
        if (is_bool($v)) return $v ? 'true' : 'false';
        if ($v === null) return 'null';
        if (is_array($v)) {
            if ($v === []) {
                return '[]';
            }
            $isList = self::isList($v);
            $pad    = str_repeat(' ', $indent);
            $padIn  = str_repeat(' ', $indent + 4);
            $out = "[\n";
            foreach ($v as $k => $sub) {
                $line = $padIn;
                if (!$isList) {
                    if (is_int($k)) {
                        if ($k < -self::MAX_INT_ABS || $k > self::MAX_INT_ABS) {
                            throw new \RuntimeException('Array key integer out of bounds.');
                        }
                        $line .= $k . ' => ';
                    } elseif (is_string($k)) {
                        $line .= self::renderStringLiteral($k) . ' => ';
                    } else {
                        throw new \RuntimeException('Array keys must be string or int.');
                    }
                }
                $line .= $this->renderValue($sub, $indent + 4, $depth + 1) . ",\n";
                $out .= $line;
            }
            $out .= $pad . ']';
            return $out;
        }
        throw new \RuntimeException('Unsupported value type in config payload: ' . get_debug_type($v));
    }

    /**
     * Render a PHP single-quoted string literal.
     *
     * Inside a single-quoted PHP literal only `\\` and `\'` are
     * special; every other byte is taken verbatim. We still reject
     * a wide set of bytes so the resulting `.php` source stays
     * sane to read in a diff and so a hypothetical future "value
     * gets pulled into a header / log line" can't be tricked into
     * a CR/LF / NUL injection.
     *
     * Allowed bytes:
     *   - TAB (0x09) and LF (0x0A) — operator might legitimately
     *     embed newlines via a future edit; PHP tolerates them in
     *     single-quoted literals.
     *   - 0x20..0x7E (printable ASCII)
     *   - 0x80..0xFF (UTF-8 multi-byte starts and continuations).
     *     We do not validate UTF-8 sequence well-formedness here —
     *     `validateShape` already rejects ill-formed-UTF-8 strings
     *     in the targets we write.
     *
     * Forbidden:
     *   - 0x00 (NUL), 0x0D (CR), 0x01..0x08, 0x0B, 0x0C, 0x0E..0x1F,
     *     0x7F (DEL).
     */
    private static function renderStringLiteral(string $v): string
    {
        if (strlen($v) > self::MAX_STRING_LEN) {
            throw new \RuntimeException(
                'String exceeds ' . self::MAX_STRING_LEN . '-byte limit (got ' . strlen($v) . ').'
            );
        }
        $len = strlen($v);
        for ($i = 0; $i < $len; $i++) {
            $c = ord($v[$i]);
            if ($c === 0x09 || $c === 0x0A) continue;
            if ($c >= 0x20 && $c !== 0x7F) continue;
            throw new \RuntimeException(
                'String contains forbidden control byte 0x' . sprintf('%02X', $c) . ' at offset ' . $i . '.'
            );
        }
        return "'" . strtr($v, ["\\" => "\\\\", "'" => "\\'"]) . "'";
    }

    /**
     * @param array<int|string, mixed> $a
     */
    private static function isList(array $a): bool
    {
        $i = 0;
        foreach (array_keys($a) as $k) {
            if ($k !== $i) return false;
            $i++;
        }
        return true;
    }
}
